### ISSUE TITLE
Ollama api key authentication

### ISSUE THREAD

**Issue by gnpaone** [tak-bro/aicommit2#90]
### Feature request

I have Ollama hosted in a server with authentication. It provides api key and jwt token. I want to use my hosted server.

### Why?

I want to use Ollama, since it have authentication it won't work with just setting `host` config.

### Alternatives

Yes, a bearer token can be added while creating new Ollama

```ts
this.ollama = new Ollama({
    host: this.host,
    headers: { 'Authorization': `Bearer ${this.apiKey}` },
});
```

### Additional context

https://github.com/ollama/ollama/issues/1053#issuecomment-2389752279

**Comment by tak-bro** [comment]
@gnpaone I will soon update so that you can set the api key in Ollama as well.

**Comment by tak-bro** [comment]
@gnpaone Hello, I updated code to add [`key`](https://github.com/tak-bro/aicommit2/issues/90) option for Ollama. But I haven't done an accurate test. Can you try it and let me know the results?

**Comment by gnpaone** [comment]
Okay I'll test it

**Comment by gnpaone** [comment]
I'll do some troubleshooting from my side and follow up

**Comment by gnpaone** [comment]
I did some troubleshooting

![image](https://github.com/user-attachments/assets/6c3ca5da-25a2-4371-9b05-6b436dcaa093)

there's api key and jwt token but I get 401 error even using curl, but basic auth is working fine ie https://username:password@host.com using curl but not working in aicommit2 for some reason

![image](https://github.com/user-attachments/assets/7679f8fe-d419-4f21-a19b-692bbf5cb3a2)

**Comment by gnpaone** [comment]
![image](https://github.com/user-attachments/assets/c2f4b0fd-e068-4bfc-a3f4-d57104e38595)

**Comment by gnpaone** [comment]
Update: I've created a new pr in the ollama-js package repo, which should fix the issues and thus ollama can be initialized with
```ts
this.ollama = new Ollama({
    host: this.host,
    headers: { 'Authorization': `Bearer ${this.apiKey}` },
});
```
for api key
```ts
this.ollama = new Ollama({
    host: this.host,
    headers: { 'Authorization': `Basic ${this.base64encodedtext}` }, // username:password base64 encoded
});
```
for basic auth

This can be generalized something like
```ts
constructor({ host, apiKey, base64encodedText, jwtToken }: 
  { host: string; apiKey?: string; base64encodedText?: string; jwtToken?: string }) {
  this.host = host;
  this.ollamaHeaders = this.createOllamaAuthHeader(apiKey, base64encodedText, jwtToken);
  this.ollama = new Ollama({
      host: this.host,
      headers: this.ollamaHeaders,
  });
}

createOllamaAuthHeader(apiKey?: string, base64encodedText?: string, jwtToken?: string) {
  if (apiKey) {
    return { 'Authorization': Bearer ${apiKey} };
  } else if (base64encodedText) {
    return { 'Authorization': Basic ${base64encodedText} };
  } else if (jwtToken) {
    return { 'Authorization': JWT ${jwtToken} };
  } else {
    return {};
  }
}
```

**Comment by gnpaone** [comment]
@tak-bro Actually there's a way for you test it

You can use docker to test it
docker-compose.yml:
```yaml
version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ollama_net_data:/root/.ollama
    environment:
      OLLAMA_ORIGINS: "*"
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - ollama_net

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - ollama_net

networks:
  ollama_net:
    driver: bridge

volumes:
  ollama_net_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
```
Caddyfile:
```Caddyfile
http://ollamaapi.localhost {
   basicauth / {
      username passwordhash
   }
   
   header Access-Control-Allow-Origin "*"
   header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, HEAD, DELETE"
   header Access-Control-Allow-Headers "Content-Type, Authorization"
   header Access-Control-Allow-Credentials "true"
    
   reverse_proxy / ollama:11434 {
      header_up Access-Control-Allow-Origin {http.request.header.Origin}
      header_up Access-Control-Allow-Credentials "true"
   }
}
```
(Replace passwordhash with [bcrypt password hash](https://bcrypt.online/) where plainn text is the password)

http://127.0.0.1:11434 is ollama api as usual and same can be accessed via http://ollamaapi.localhost with authentication
